// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rekeningrijden.PricingService.Data;

namespace Rekeningrijden.PricingService.Migrations
{
    [DbContext(typeof(LocationContext))]
    [Migration("20190614091121_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rekeningrijden.PricingService.Model.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Rekeningrijden.PricingService.Model.PriceHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<long?>("LocationId");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("PriceHistoryEntry");
                });

            modelBuilder.Entity("Rekeningrijden.PricingService.Model.PriceHistoryEntry", b =>
                {
                    b.HasOne("Rekeningrijden.PricingService.Model.Location")
                        .WithMany("PriceHistory")
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
